import * as fs from "fs";
import * as path from "path";

/**
 * Where the API corpus (written by the in-game dump_game_api tool) lives. Both sides default
 * to %LOCALAPPDATA%\RimAgentic\api\api-corpus.jsonl; RIMAGENTIC_API overrides.
 */
function corpusPath(): string {
    if (process.env.RIMAGENTIC_API) return process.env.RIMAGENTIC_API;
    const local = process.env.LOCALAPPDATA || path.join(process.env.USERPROFILE || "", "AppData", "Local");
    return path.join(local, "RimAgentic", "api", "api-corpus.jsonl");
}

// Parse once and cache; reload if the file changed (a fresh dump_game_api run).
let cache: { path: string; mtime: number; records: any[] } | null = null;
function loadCorpus(): any[] | null {
    const p = corpusPath();
    if (!fs.existsSync(p)) return null;
    const mtime = fs.statSync(p).mtimeMs;
    if (cache && cache.path === p && cache.mtime === mtime) return cache.records;
    const records: any[] = [];
    for (const line of fs.readFileSync(p, "utf8").split("\n")) {
        const t = line.trim();
        if (!t) continue;
        try { records.push(JSON.parse(t)); } catch { /* skip a bad line */ }
    }
    cache = { path: p, mtime, records };
    return records;
}

export const apiSearchTools = [
    {
        name: "search_game_api",
        description:
            "Search the RimWorld C# API corpus (public Verse/RimWorld types + members, generated by the " +
            "in-game dump_game_api tool) for a query — e.g. 'apply hediff', 'TakeDamage', 'spawn thing', " +
            "'weather'. Returns matching types with the relevant members' signatures so you can write " +
            "correct C#/Harmony against the real API instead of guessing. If the corpus is missing, run " +
            "'dump_game_api' via execute_game_tool in a running RimWorld first.",
        inputSchema: {
            type: "object",
            properties: {
                query: { type: "string", description: "Keywords/concept to find; matches type names, member names, and signatures." },
                kind: { type: "string", description: "Optional filter by type kind: 'class', 'struct', 'enum', 'interface', 'static class', 'abstract class'." },
                limit: { type: "number", description: "Max types to return (default 15)." }
            },
            required: ["query"]
        }
    }
];

export async function handleApiSearchTool(name: string, args: any) {
    if (name !== "search_game_api") throw new Error(`Unknown api-search tool: ${name}`);

    const records = loadCorpus();
    if (!records) {
        return { content: [{ type: "text", text: `API corpus not found at ${corpusPath()}. Run the in-game 'dump_game_api' tool (via execute_game_tool) in a running RimWorld to generate it, then retry.` }] };
    }

    // Drop common words and 1-char tokens — "spawn thing at" shouldn't rank on "at".
    const STOP = new Set(["a", "an", "the", "at", "in", "on", "to", "of", "for", "with", "and", "or", "is", "as", "by", "from", "into", "how", "do", "i", "get", "set"]);
    const terms = String(args.query || "").toLowerCase().split(/\s+/)
        .filter(t => t.length >= 2 && !STOP.has(t));
    if (terms.length === 0) return { content: [{ type: "text", text: "Provide a 'query' with at least one meaningful term." }] };
    const kind = args.kind ? String(args.kind).toLowerCase() : null;
    const limit = Math.max(1, Math.min(50, Number(args.limit) || 15));

    const scored: Array<{ rec: any; score: number; matched: any[] }> = [];
    for (const rec of records) {
        if (kind && String(rec.kind || "").toLowerCase() !== kind) continue;
        const typeName = String(rec.name || "").toLowerCase();
        const full = String(rec.full || "").toLowerCase();

        let score = 0;
        for (const term of terms) {
            if (typeName === term) score += 20;
            else if (typeName.includes(term)) score += 8;
            if (full.includes(term)) score += 1;
        }

        const matched: any[] = [];
        let memberScore = 0;
        for (const m of rec.members || []) {
            const mn = String(m.name || "").toLowerCase();
            const sig = String(m.sig || "").toLowerCase();
            let ms = 0;
            for (const term of terms) {
                if (mn === term) ms += 10;
                else if (mn.includes(term)) ms += 4;
                else if (sig.includes(term)) ms += 1;
            }
            if (ms > 0) { matched.push({ ...m, _s: ms }); memberScore += ms; }
        }
        // Cap member contribution so a type with dozens of trivial substring matches (e.g. a
        // *DefOf with many fields) can't outrank a type whose name/members truly match.
        score += Math.min(memberScore, 30);
        // Reward matching more of the distinct query terms (across type + members).
        const distinctHit = terms.filter(t =>
            typeName.includes(t) || (rec.members || []).some((m: any) => String(m.name || "").toLowerCase().includes(t))
        ).length;
        if (distinctHit > 1) score += distinctHit * 5;
        if (score > 0) scored.push({ rec, score, matched });
    }

    scored.sort((a, b) => b.score - a.score);
    const results = scored.slice(0, limit).map(({ rec, matched }) => {
        const members = (matched.length ? matched.sort((a, b) => b._s - a._s) : (rec.members || []).slice(0, 8))
            .slice(0, 15)
            .map((m: any) => `${m.stat ? "static " : ""}${m.kind} ${m.sig}`);
        return {
            type: `${rec.kind} ${rec.full}${rec.baseType ? ` : ${rec.baseType}` : ""}`,
            members
        };
    });

    return {
        content: [{
            type: "text",
            text: JSON.stringify({ query: args.query, corpusTypes: records.length, matches: results.length, results }, null, 2)
        }]
    };
}
